"""
generate_puml_class_diagrams.py
--------------------------------
Auto-generates docs/class_diagram.puml from the pythermonet source tree.
Uses only the standard library (ast, pathlib).

Run from the repository root:
    python scripts/generate_puml_class_diagrams.py
"""
from __future__ import annotations

import ast
from collections import defaultdict
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parents[1]
SRC_ROOT  = REPO_ROOT / "src" / "pythermonet"
OUTPUT    = REPO_ROOT / "docs" / "class_diagram.puml"

HEADER = """\
@startuml pythermonetII

' Auto-generated by scripts/generate_puml_class_diagrams.py — do not edit manually.

skinparam classAttributeIconSize 0
skinparam classFontSize 12
skinparam groupInheritance 2
hide empty members
"""

FOOTER = "@enduml\n"

EXCLUDE_FILES = {"__init__.py"}


# ---------------------------------------------------------------------------
# AST helpers
# ---------------------------------------------------------------------------

def _dataclass_info(node: ast.ClassDef) -> tuple[bool, bool]:
    """Return (is_dataclass, is_frozen)."""
    for dec in node.decorator_list:
        name, keywords = None, {}
        if isinstance(dec, ast.Name):
            name = dec.id
        elif isinstance(dec, ast.Call):
            func = dec.func
            name = func.id if isinstance(func, ast.Name) else (
                func.attr if isinstance(func, ast.Attribute) else None
            )
            keywords = {
                kw.arg: kw.value
                for kw in dec.keywords
                if isinstance(kw.value, ast.Constant)
            }
        if name == "dataclass":
            frozen_node = keywords.get("frozen")
            frozen = bool(frozen_node.value) if frozen_node else False
            return True, frozen
    return False, False


def _fields(node: ast.ClassDef) -> list[tuple[str, str]]:
    result = []
    for stmt in node.body:
        if isinstance(stmt, ast.AnnAssign) and isinstance(stmt.target, ast.Name):
            name = stmt.target.id
            if not name.startswith("_"):
                result.append((name, ast.unparse(stmt.annotation)))
    return result


def _properties(node: ast.ClassDef) -> list[tuple[str, str]]:
    result = []
    for stmt in node.body:
        if isinstance(stmt, ast.FunctionDef):
            for dec in stmt.decorator_list:
                if isinstance(dec, ast.Name) and dec.id == "property":
                    ret = ast.unparse(stmt.returns) if stmt.returns else ""
                    result.append((stmt.name, ret))
                    break
    return result


def _factory_methods(node: ast.ClassDef) -> list[str]:
    result = []
    for stmt in node.body:
        if isinstance(stmt, ast.FunctionDef):
            for dec in stmt.decorator_list:
                if isinstance(dec, ast.Name) and dec.id == "classmethod":
                    result.append(stmt.name)
                    break
    return result


def _bases(node: ast.ClassDef) -> list[str]:
    out = []
    for base in node.bases:
        if isinstance(base, ast.Name):
            out.append(base.id)
        elif isinstance(base, ast.Attribute):
            out.append(base.attr)
    return out


def _class_refs(annotation: str, known: set[str]) -> list[str]:
    """Find known class names referenced inside a type annotation."""
    try:
        tree = ast.parse(annotation, mode="eval")
    except SyntaxError:
        return []
    return [
        n.id for n in ast.walk(tree.body)
        if isinstance(n, ast.Name) and n.id in known
    ]


def _is_many(annotation: str) -> bool:
    low = annotation.lower()
    return any(low.startswith(p) for p in ("list[", "sequence[", "tuple["))


def _fmt_type(annotation: str) -> str:
    return annotation.replace("np.ndarray", "ndarray").replace("numpy.ndarray", "ndarray")


# ---------------------------------------------------------------------------
# Source scanning
# ---------------------------------------------------------------------------

ClassInfo = tuple[str, bool, bool, list[tuple[str, str]], list[str], list[tuple[str, str]], list[str]]
# name, is_dataclass, frozen, fields, bases, properties, factory_methods


def scan() -> dict[str, list[ClassInfo]]:
    packages: dict[str, list[ClassInfo]] = defaultdict(list)
    for py_file in sorted(SRC_ROOT.rglob("*.py")):
        if py_file.name in EXCLUDE_FILES:
            continue
        try:
            tree = ast.parse(py_file.read_text(encoding="utf-8"))
        except (SyntaxError, UnicodeDecodeError):
            continue

        # Top-level package folder name (e.g. "core", "components", ...)
        rel_parts = py_file.relative_to(SRC_ROOT).parts
        pkg = rel_parts[0] if len(rel_parts) > 1 else "pythermonet"

        for node in ast.walk(tree):
            if not isinstance(node, ast.ClassDef):
                continue
            if node.name.startswith("_"):
                continue
            is_dc, frozen = _dataclass_info(node)
            packages[pkg].append((
                node.name, is_dc, frozen,
                _fields(node), _bases(node),
                _properties(node), _factory_methods(node),
            ))

    return dict(packages)


# ---------------------------------------------------------------------------
# PlantUML generation
# ---------------------------------------------------------------------------

def _relationships(packages: dict[str, list[ClassInfo]], known: set[str]) -> dict[str, list[str]]:
    result: dict[str, list[str]] = {pkg: [] for pkg in packages}
    seen: set[str] = set()

    for pkg, classes in packages.items():
        for cls_name, _, _, fields, bases, *_ in classes:
            # Inheritance
            for base in bases:
                if base in known:
                    line = f"  {base} <|-- {cls_name}"
                    if line not in seen:
                        result[pkg].append(line)
                        seen.add(line)
            # Composition / aggregation from field types
            for _, annotation in fields:
                refs = _class_refs(annotation, known)
                for ref in refs:
                    if ref == cls_name:
                        continue
                    many = _is_many(annotation)
                    line = (f'  {cls_name} o-- "many" {ref}' if many
                            else f"  {cls_name} *-- {ref}")
                    if line not in seen:
                        result[pkg].append(line)
                        seen.add(line)

    return result


def generate(packages: dict[str, list[ClassInfo]]) -> str:
    known = {name for classes in packages.values() for name, *_ in classes}
    rels = _relationships(packages, known)
    parts = [HEADER]

    for pkg in sorted(packages):
        parts.append(f"\n' {'─' * 41}")
        parts.append(f"' {pkg.capitalize()}")
        parts.append(f"' {'─' * 41}")
        parts.append(f'package "{pkg}" {{')
        for name, is_dc, frozen, fields, _, properties, factory_methods in packages[pkg]:
            if is_dc and frozen:
                stereotype = "<<dataclass, frozen>>"
            elif is_dc:
                stereotype = "<<dataclass>>"
            else:
                stereotype = ""
            parts.append(f"  class {name} {stereotype} {{")
            if fields:
                parts.append("  ..attribute..")
                for fname, ftype in fields:
                    parts.append(f"    +{fname}: {_fmt_type(ftype)}")
            if properties:
                parts.append("  ..property..")
                for pname, ptype in properties:
                    if ptype:
                        parts.append(f"    +{pname}: {_fmt_type(ptype)}")
                    else:
                        parts.append(f"    +{pname}")
            if factory_methods:
                parts.append("  ..factory..")
                for mname in factory_methods:
                    parts.append(f"    +{mname}()")
            parts.append("  }")
        if rels.get(pkg):
            parts.append("")
            parts.extend(rels[pkg])
        parts.append("}")

    parts.append("")
    parts.append(FOOTER)
    return "\n".join(parts)


# ---------------------------------------------------------------------------
# Entry point
# ---------------------------------------------------------------------------

def main() -> None:
    packages = scan()
    OUTPUT.write_bytes(generate(packages).encode("utf-8"))
    n = sum(len(v) for v in packages.values())
    print(f"Written {OUTPUT.relative_to(REPO_ROOT)}  ({n} dataclasses)")


if __name__ == "__main__":
    main()
